"""initial schema

Revision ID: fed22ea7434d
Revises:
Create Date: 2026-07-03 01:03:46.755821
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = 'fed22ea7434d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('first_seen_step', sa.Integer(), nullable=True),
    sa.Column('is_merchant', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('counterparties',
    sa.Column('counterparty_id', sa.String(), nullable=False),
    sa.Column('is_merchant', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('counterparty_id')
    )
    op.create_table('model_versions',
    sa.Column('model_version_id', sa.String(), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('feature_set', sa.String(), nullable=True),
    sa.Column(
        'metrics',
        sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
        nullable=True,
    ),
    sa.Column(
        'calibration',
        sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
        nullable=True,
    ),
    sa.Column('leakage_verdict', sa.String(), nullable=True),
    sa.Column(
        'df1_result',
        sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
        nullable=True,
    ),
    sa.Column('artifact_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('model_version_id')
    )
    op.create_table('transactions',
    sa.Column('txn_id', sa.String(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('event_ts', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('counterparty_id', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('bal_orig_before', sa.Numeric(), nullable=True),
    sa.Column('bal_orig_after', sa.Numeric(), nullable=True),
    sa.Column('bal_dest_before', sa.Numeric(), nullable=True),
    sa.Column('bal_dest_after', sa.Numeric(), nullable=True),
    sa.Column('sim_flagged', sa.Boolean(), nullable=False),
    sa.Column('label', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.counterparty_id'], ),
    sa.PrimaryKeyConstraint('txn_id')
    )
    op.create_index(
        'ix_transactions_account_ts', 'transactions', ['account_id', 'event_ts'], unique=False
    )
    op.create_index(
        'ix_transactions_counterparty', 'transactions', ['counterparty_id'], unique=False
    )
    op.create_index('ix_transactions_event_ts', 'transactions', ['event_ts'], unique=False)
    op.create_table('cases',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('txn_id', sa.String(), nullable=False),
    sa.Column('model_version_id', sa.String(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('score_band', sa.String(), nullable=False),
    sa.Column('recommendation_action', sa.String(), nullable=False),
    sa.Column('recommendation_confidence', sa.String(), nullable=False),
    sa.Column(
        'recommendation_basis',
        sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
        nullable=False,
    ),
    sa.Column('uncertainty_flag', sa.Boolean(), nullable=False),
    sa.Column(
        'evidence',
        sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
        nullable=False,
    ),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('explanation_pathway', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('queue_priority', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.model_version_id'], ),
    sa.ForeignKeyConstraint(['txn_id'], ['transactions.txn_id'], ),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('txn_id')
    )
    op.create_index('ix_cases_score', 'cases', ['score'], unique=False)
    op.create_index('ix_cases_status_priority', 'cases', ['status', 'queue_priority'], unique=False)
    op.create_table('audit_log',
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column(
        'payload',
        sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
        nullable=False,
    ),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(
        'ix_audit_log_case_created', 'audit_log', ['case_id', 'created_at'], unique=False
    )
    op.create_table('dispositions',
    sa.Column('disposition_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('deviated_from_recommendation', sa.Boolean(), nullable=False),
    sa.Column('follow_up', sa.Text(), nullable=True),
    sa.Column('analyst_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('disposition_id')
    )
    op.create_index('ix_dispositions_case', 'dispositions', ['case_id'], unique=False)
    op.create_table('rule_hits',
    sa.Column('rule_hit_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column(
        'evidence',
        sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
        nullable=False,
    ),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('rule_hit_id')
    )
    op.create_index('ix_rule_hits_case', 'rule_hits', ['case_id'], unique=False)
    # ### end Alembic commands ###

    # Append-only enforcement on audit_log (FR-20, NFR-3). Postgres only; the
    # application also guarantees this via the insert-only Audit Writer, and
    # production revokes UPDATE/DELETE at the database role level (NFR-7).
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            CREATE OR REPLACE FUNCTION tfm_audit_log_no_mutate()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'audit_log is append-only: % not permitted', TG_OP;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        op.execute(
            """
            CREATE TRIGGER tfm_audit_log_append_only
            BEFORE UPDATE OR DELETE ON audit_log
            FOR EACH ROW EXECUTE FUNCTION tfm_audit_log_no_mutate();
            """
        )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS tfm_audit_log_append_only ON audit_log;")
        op.execute("DROP FUNCTION IF EXISTS tfm_audit_log_no_mutate();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rule_hits_case', table_name='rule_hits')
    op.drop_table('rule_hits')
    op.drop_index('ix_dispositions_case', table_name='dispositions')
    op.drop_table('dispositions')
    op.drop_index('ix_audit_log_case_created', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_cases_status_priority', table_name='cases')
    op.drop_index('ix_cases_score', table_name='cases')
    op.drop_table('cases')
    op.drop_index('ix_transactions_event_ts', table_name='transactions')
    op.drop_index('ix_transactions_counterparty', table_name='transactions')
    op.drop_index('ix_transactions_account_ts', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('model_versions')
    op.drop_table('counterparties')
    op.drop_table('accounts')
    # ### end Alembic commands ###
